Atech.SGR.WebGerenciador/Controllers/TriggerRulesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Compass.XFracas.WebGerenciadorInterface.Model;

namespace Compass.XFracas.WebGerenciador.Controllers
{
    public class TriggerRulesController : CommonController
    {
        // GET: TriggerRules
        public ActionResult Index()
        {

            List<Trigger> lstTrigger = new List<Trigger>();

            ViewBag.lstTrigger = lstTrigger;

            return View();
        }




    }
}

Atech.SGR.WebGerenciador/Views/TriggerRules/Index.cshtml
<style>

    .dataTables_filter {
        text-align: left !important;
    }

        .dataTables_filter input {
            width: 350px !important;
        }
</style>


<div class="col-span-12">
    <br />

    <div id="dialog-confirm" class="hide">

        <div class="space-6"></div>

        <p class="bigger-110 bolder center grey">

            Deseja mesmo exluir esta informação?
        </p>
    </div><!-- #dialog-confirm -->

    <div id="criar-trigger" class="hide">

        <div class="space-6"></div>

        <form id="form-criar-trigger">
            <fieldset>
                <div class="form-group">
                    <label class="block clearfix">
                        <span class="block input-icon input-icon-right">
                            <input type="text" id="txtNomeHierarquia" name="txtNomeHierarquia" class="form-control" placeholder="" />
                        </span>
                    </label>
                </div>

             
            </fieldset>
        </form>
    </div><!-- #criar-lda -->


    <div class="row">
        <div class="col-xs-12" style="float:left;padding-left:1%!important">
            <button type="button" onclick="CriarTrigger()" class="btn--search btn btn-primary">
                <i class="fa fa-plus" aria-hidden="true"></i>
                <span class="ml-2">Adicionar</span>
            </button>

        </div>
    </div>


    <div class="space-6"></div>

    <div class="pull-right tableTools-container"></div>

    <table class="table card" id="table-trigger">
        <thead>
            <tr>
                <th>
                    Hierarquia
                    <i class="fa fa-caret-up ml-4 p-2" style="font-size:1.2rem;"></i>
                </th>
                <th>Ativa?</th>
                <th>Expressão</th>
                <th>Recorrência (dias)</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
    </table>
</div>


<!-- page specific plugin scripts -->
<script src="~/assets/js/jquery.dataTables.min.js"></script>
<script src="~/assets/js/jquery.dataTables.bootstrap.min.js"></script>
<script src="~/assets/js/dataTables.buttons.min.js"></script>
<script src="~/assets/js/buttons.flash.min.js"></script>
<script src="~/assets/js/buttons.html5.min.js"></script>
<script src="~/assets/js/buttons.print.min.js"></script>
<script src="~/assets/js/buttons.colVis.min.js"></script>
<script src="~/assets/js/dataTables.select.min.js"></script>

<script>


    $(document).on('keypress', function (e) {
        if (e.which == 13 || e.keyCode == 13) {
            SalvarTrigger();
        }
    });


    var atualizar = false;
    jQuery(function ($) {
        var myTable =
            $('#table-trigger')
                .DataTable({

                    "data": @Html.Raw(Json.Encode(@ViewBag.lstTrigger)),
                    "ajax": {
                        "url": '@Url.Action("ListarTrigger", "TriggerRules")',
                        "type": "POST",
                        "dataSrc": function (json) {
                            if (atualizar) {
                                return json;
                            }
                        }
                    },
                    "columns": [
                      

                        { "data": "hierarquia" },
                        { "data": "ativo" },
                        { "data": "expressao" },
                        { "data": "recorrencia_dias" },
                                        
                        {
                            "mData": null,
                            "mRender": function (obj) {
                                if ('@ViewBag.Deletar' != "disabled")
                                    return '<a  style="cursor:pointer" id="' + obj.Id + '" onclick="javascript:excluir(\'' + obj.Id + '\');return false;" data-toggle="tooltip" data-placement="top" data-html="true"><i title="Excluir" class="fa fa-times" style="font-size:2.5rem;"></i></a>';
                                else
                                    return "";
                            },
                            "orderable": false
                        }
                    ],

                    bAutoWidth: false,
                    "aaSorting": [],
                    "bFilter": true,
                    "bLengthChange": false,
                    "bInfo": true,
                    "iDisplayLength": 10,
                    "bPaginate": true,

                    "oLanguage": {
                        "sProcessing": '@Compass.Reliability.WebApp.Resources.ResourceForAll.Usuario_lst_sprocessing',
                        "sLengthMenu": '@Compass.Reliability.WebApp.Resources.ResourceForAll.Usuario_lst_slengthmenu',
                        "sZeroRecords": '@Compass.Reliability.WebApp.Resources.ResourceForAll.Usuario_lst_szerorecords',
                        "sInfo": '@Compass.Reliability.WebApp.Resources.ResourceForAll.Usuario_lst_sinfo',
                        "sInfoEmpty": '@Compass.Reliability.WebApp.Resources.ResourceForAll.Usuario_lst_sinfoempty',
                        "sInfoFiltered": "",
                        "sInfoPostFix": "",
                        "sSearch": '@Compass.Reliability.WebApp.Resources.ResourceForAll.Usuario_lst_ssearch',
                        "sUrl": "",
                        "oPaginate": {

                            "sPrevious": "<",
                            "sNext": ">"
                        }
                    }
                });

        $.fn.dataTable.Buttons.defaults.dom.container.className = 'dt-buttons btn-overlap btn-group btn-overlap';

        new $.fn.dataTable.Buttons(myTable, {
            buttons: [
                {
                    "extend": "colvis",
                    "text": "<i class='fa fa-search bigger-110 blue'></i> <span class='hidden'>'@Compass.Reliability.WebApp.Resources.ResourceForAll.LDA_index_Show_coluna'</span>",
                    "className": "btn btn-white btn-primary btn-bold",
                    columns: ':not(:last)'
                },
                {
                    "extend": "copy",
                    "text": "<i class='fa fa-copy bigger-110 pink'></i> <span class='hidden'>'@Compass.Reliability.WebApp.Resources.ResourceForAll.LDA_index_copy'</span>",
                    "className": "btn btn-white btn-primary btn-bold"
                },
                {
                    "extend": "csv",
                    "text": "<i class='fa fa-database bigger-110 orange'></i> <span class='hidden'>'@Compass.Reliability.WebApp.Resources.ResourceForAll.LDA_index_export_csv'</span>",
                    "className": "btn btn-white btn-primary btn-bold"
                },
                {
                    "extend": "excel",
                    "text": "<i class='fa fa-file-excel-o bigger-110 green'></i> <span class='hidden'>'@Compass.Reliability.WebApp.Resources.ResourceForAll.LDA_index_excel'</span>",
                    "className": "btn btn-white btn-primary btn-bold"
                },
                {
                    "extend": "pdf",
                    "text": "<i class='fa fa-file-pdf-o bigger-110 red'></i> <span class='hidden'>'@Compass.Reliability.WebApp.Resources.ResourceForAll.LDA_index_pdf'</span>",
                    "className": "btn btn-white btn-primary btn-bold"
                },
                {
                    "extend": "print",
                    "text": "<i class='fa fa-print bigger-110 grey'></i> <span class='hidden'>'@Compass.Reliability.WebApp.Resources.ResourceForAll.LDA_index_print'</span>",
                    "className": "btn btn-white btn-primary btn-bold",
                    autoPrint: false
                }
            ]
        });
        myTable.buttons().container().appendTo($('.tableTools-container'));

        //style the message box
        var defaultCopyAction = myTable.button(1).action();
        myTable.button(1).action(function (e, dt, button, config) {
            defaultCopyAction(e, dt, button, config);
            $('.dt-button-info').addClass('gritter-item-wrapper gritter-info gritter-center white');
        });


        var defaultColvisAction = myTable.button(0).action();
        myTable.button(0).action(function (e, dt, button, config) {

            defaultColvisAction(e, dt, button, config);


            if ($('.dt-button-collection > .dropdown-menu').length == 0) {
                $('.dt-button-collection')
                    .wrapInner('<ul class="dropdown-menu dropdown-light dropdown-caret dropdown-caret" />')
                    .find('a').attr('href', '#').wrap("<li />")
            }
            $('.dt-button-collection').appendTo('.tableTools-container .dt-buttons')
        });

        ////

        setTimeout(function () {
            $($('.tableTools-container')).find('a.dt-button').each(function () {
                var div = $(this).find(' > div').first();
                if (div.length == 1) div.tooltip({ container: 'body', title: div.parent().text() });
                else $(this).tooltip({ container: 'body', title: $(this).text() });
            });
        }, 500);



    });


    function Atualizar() {
        atualizar = true;
        var table = $('#table-trigger').DataTable();
        table.ajax.reload(null, false);
    }

 


        var id_trigger;

        function excluir(id) {

            id_trigger = id;

            $("#dialog-confirm").removeClass('hide').dialog({
                resizable: false,
                width: '320',
                modal: true,
                title: 'Excluir',
                title_html: true,
                buttons: [
                    {
                        html: "<i class='ace-icon fa fa-trash-o bigger-110'></i>&nbsp; Excluir",
                        "class": "btn btn-danger btn-minier",
                        click: function () {
                            ProsseguirExclusao()
                            $(this).dialog("close");
                        }
                    }
                    ,
                    {
                        html: "<i class='ace-icon fa fa-times bigger-110'></i>&nbsp; Cancelar",
                        "class": "btn btn-minier",
                        click: function () {
                            $(this).dialog("close");
                        }
                    }
                ]
            });
    }

    function CriarTrigger() {

            $("#txtNomeHierarquia").val("");


            $("#criar-trigger").removeClass('hide').dialog({
                resizable: false,
                width: '320',
                closeOnEscape: false,
                modal: true,
                title: 'Criar',
                title_html: true,
                buttons: [
                    {
                        html: "<i class='ace-icon fa fa-sucess bigger-110'></i>&nbsp; Salvar",
                        "class": "btn btn-primary btn-minier",
                        click: function () {
                            SalvarLDA()
                            $(this).dialog("close");
                        }
                    }
                    ,
                    {
                        html: "<i class='ace-icon fa fa-times bigger-110'></i>&nbsp; Cancelar",
                        "class": "btn btn-minier",
                        click: function () {
                            $(this).dialog("close");
                        }
                    }
                ]
            });
        }


        function ProsseguirExclusao() {
            ExcluirTrigger();
       }

     function ExcluirTrigger() {

            //StartProgress();
            $.ajax({
                url: '@Url.Action("ExcluirTrigger", "TriggerRules")',
                dataType: 'json',
                data: {
                    "id": id_trigger
                },
                type: 'POST'
            }).success(function (data) {
                //EndProgress();
                if (data != "OK") {
                    MessageShow('Erro ao executar o processo, contate o administrador do sistema.')
                }
                else {
                    MessageShow('Trigger excluida com sucesso.')
                }

                Atualizar();

                }).fail(function () {
                    EndProgress();
                    MessageShow('Erro ao executar o processo, contate o administrador do sistema.')
            });
    }







    function SalvarTrigger() {


        if ($("#txtNomeHierarquia").val() != "") {
            $.ajax({
                url: '@Url.Action("SalvarTrigger", "TriggerRules")',
                dataType: 'json',
                data: {
                    "nomehierarquia": $("#txtNomeHierarquia").val(),
                },
                type: 'POST'
            }).success(function (data) {

               MessageShow('Dados salvos com sucesso!')

            }).fail(function () {
                EndProgress();
                MessageShow('Erro ao executar o processo, contate o administrador do sistema.')
            });
        }
        else {
            MessageShow('Nome Hierarquia e obrigatório.')
        }
    }



</script>